export const FETCH_CONTENT_REQUEST = 'FETCH_CONTENT_REQUEST';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_FAILURE = 'FETCH_CONTENT_FAILURE';
export const DISCARD_CONTENT = 'DISCARD_CONTENT';

export const CHANGE_LOCATION = 'CHANGE_LOCATION';
