export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const DISCARD_DATA = 'DISCARD_DATA';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';
